from __future__ import annotations

from pydantic import BaseModel, Field


class Citation(BaseModel):
    """A page-level citation extracted from a generated answer."""

    document_name: str
    page_number: int
    source_text: str = Field(..., description="The chunk text the claim was drawn from")


class AnswerResponse(BaseModel):
    """Structured answer produced by the generation layer."""

    answer: str
    citations: list[Citation]
    model_used: str = "gemini-2.5-pro"
    chunks_used: int = 0


class DocumentInfo(BaseModel):
    """Lightweight summary of an indexed document, derived from Qdrant payloads."""

    document_name: str
    doc_id: str
    chunk_count: int
    total_pages: int


class CompareResponse(BaseModel):
    """Side-by-side comparison of two documents generated by Gemini."""

    document_name_a: str
    document_name_b: str
    comparison: str
    citations_a: list[Citation] = Field(default_factory=list)
    citations_b: list[Citation] = Field(default_factory=list)
    model_used: str = "gemini-2.5-pro"
